WIDTH = 600
HEIGHT = 600

# number guessing
MAX_TRIES = 7

# quiz.py
QUESTIONS_COUNT = 7
QUIZ_QUESTIONS = [
["What is the capital of Australia?", ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], 2],
["Who painted the Mona Lisa?", ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'], 0],
["Which planet is known as the Red Planet?", ['Mars', 'Jupiter', 'Venus', 'Saturn'], 0],
["What is the chemical symbol for gold?", ['Ag', 'Au', 'Hg', 'Pt'], 1],
["Which country is known as the Land of the Rising Sun?", ['China', 'South Korea', 'Japan', 'Thailand'], 2],
["What is the largest organ in the human body?", ['Liver', 'Brain', 'Skin', 'Heart'], 2],
["Who wrote the play Romeo and Juliet?", ['William Shakespeare', 'Arthur Miller', 'Tennessee Williams', 'Anton Chekhov'], 0],
["What is the tallest mountain in the world?", ['Mount Kilimanjaro', 'Mount Everest', 'Mount McKinley', 'Mount Fuji'], 1],
["Which animal is known for its black and white stripes?", ['Giraffe', 'Tiger', 'Zebra', 'Penguin'], 2],
["In which year did World War II end?", ['1943', '1945', '1947', '1950'], 1],
["What is the smallest country in the world?", ['Vatican City', 'Monaco', 'Nauru', 'San Marino'], 0],
["Which scientist developed the theory of general relativity?", ['Isaac Newton', 'Albert Einstein', 'Stephen Hawking', 'Galileo Galilei'], 1],
["What is the national flower of India?", ['Lotus', 'Rose', 'Tulip', 'Sunflower'], 0],
["Which composer wrote the Symphony No. 9 in D minor, also known as the 'Choral' Symphony?", ['Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'], 0],
["Who discovered penicillin?", ['Alexander Fleming', 'Marie Curie', 'Albert Einstein', 'Louis Pasteur'], 0],
["What is the chemical formula for water?", ['H2O', 'CO2', 'NaCl', 'O2'], 0],
["Which novel is set in the fictional Maycomb County?", ['Pride and Prejudice', 'To Kill a Mockingbird', '1984', 'The Great Gatsby'], 1],
["What is the largest ocean on Earth?", ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 0],
["Who wrote the novel 'War and Peace'?", ['Fyodor Dostoevsky', 'Leo Tolstoy', 'Virginia Woolf', 'Jane Austen'], 1],
["What is the chemical symbol for iron?", ['Fe', 'Ir', 'In', 'Io'], 0],
["Which artist painted the famous artwork 'The Starry Night'?", ['Pablo Picasso', 'Vincent van Gogh', 'Salvador Dalí', 'Claude Monet'], 1],
["How many days are there in a leap year?", ['365', '366', '364', '363'], 1],
["What is the capital of France?", ['Paris', 'Rome', 'London', 'Madrid'], 0],
["I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", ['Echo', 'Whistle', 'Music', 'Wave'], 0]
]

# Hangman
HANGMAN_WORDS = [
    ('computer', 'Technology'),
    ('elephant', 'Animals'),
    ('pineapple', 'Fruits'),
    ('mountain', 'Landforms'),
    ('guitar', 'Musical Instruments'),
    ('butterfly', 'Insects'),
    ('oxygen', 'Chemical Elements'),
    ('football', 'Sports'),
    ('pizza', 'Food'),
    ('oasis', 'Geography'),
    ('painting', 'Art'),
    ('telescope', 'Science'),
    ('vampire', 'Mythical Creatures'),
    ('yoga', 'Fitness'),
    ('zodiac', 'Astrology'),
    ('avatar', 'Movies'),
    ('titanic', 'Movies'),
    ('inception', 'Movies'),
    ('jurassic park', 'Movies'),
    ('the matrix', 'Movies'),
    ('braveheart', 'Movies'),
    ('gladiator', 'Movies'),
    ('jaws', 'Movies'),
    ('pulp fiction', 'Movies'),
    ('the godfather', 'Movies'),
    ('forrest gump', 'Movies'),
    ('fight club', 'Movies'),
    ('star wars', 'Movies'),
    ('the lion king', 'Movies'),
    ('casablanca', 'Movies'),
    ('citizen kane', 'Movies'),
    ('schindlers list', 'Movies'),
    ('the green mile', 'Movies'),
    ('goodfellas', 'Movies'),
    ('the departed', 'Movies'),
    ('the truman show', 'Movies'),
    ('amelie', 'Movies'),
    ('spirited away', 'Movies'),
    ('the pianist', 'Movies'),
    ('memento', 'Movies'),
    ('birdman', 'Movies'),
    ('spotlight', 'Movies'),
    ('joker', 'Movies'),
    ('la la land', 'Movies'),
    ('get out', 'Movies'),
    ('dunkirk', 'Movies'),
    ('baby driver', 'Movies'),
    ('logan', 'Movies'),
    ('her', 'Movies'),
    ('arrival', 'Movies'),
    ('the revenant', 'Movies'),
    ('blade runner', 'Movies')
]
